## Add tool(s)

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('120s PDM Data.xlsx',sheet_name = None)

In [3]:
xls = pd.ExcelFile('120s PDM Data.xlsx')
xls.sheet_names 
flow = data.get('Flow')
flow.head()

TRAVELER TRAV DESC                            STEP NAME  \
0     V00H   100S PC              0000-00 START LOT START   
1     V00H   100S PC  5450-21 STI OXIDE BACKSIDE WET ETCH   
2     V00H   100S PC  5450-21 STI OXIDE BACKSIDE WET ETCH   
3     V00H   100S PC  5450-21 STI OXIDE BACKSIDE WET ETCH   
4     V00H   100S PC       5200-53 GATE NITRIDE DEP 2 CMP   

           RECIPE NAME                   WS             AREA  RPT MINS  \
0         PC LOT START     11-3START_WAFERS      F11 GENERAL      0.43   
1  WET_100S_SWC_DHF100   11-3DNS_SU31_DHF_4  F11 WET PROCESS      0.70   
2  WET_100S_SWC_DHF100   11-3DNS_SU3_DHF100  F11 WET PROCESS      0.70   
3  WET_100S_SWC_DHF100  11-3DNS_SU31_DHF100  F11 WET PROCESS      0.35   
4        CMP_100S_BUFF   11-3EBRA_FRXS_BUFF          F11 CMP      1.12   

   WS LOAD PCT  DISPATCH RPT SUBSET  ... SUB-FAMILY PROCESS  DENSITY  \
0        100.0           NaN      _  ...    DDR III   D100S    4 GIG   
1          0.0           NaN      _  ...    DDR III   D100S    4 GIG   
2          5.0           NaN      _  ...    DDR III   D100S    4 GIG   
3         95.0           NaN      _  ...    DDR III   D100S    4 GIG   
4        100.0           NaN      _  ...    DDR III   D100S    4 GIG   

  RPT VALIDATION STATUS MODELED UTIL AVG LOADSIZE MODELED AVAIL LOST TIME  \
0                   NaN         1.00         25.0          1.00       0.0   
1                   NaN         0.88          1.0          0.96       0.0   
2                   NaN         0.88          1.0          0.96       0.0   
3                   NaN         0.88          1.0          0.96       0.0   
4                   NaN         0.75          1.0          0.86       0.0   

  RPT BASIS MODELED CHAMBERS  
0       NaN              1.0  
1       NaN              1.0  
2       NaN              1.0  
3       NaN              1.0  
4       1.0              1.0  

[5 rows x 38 columns]

In [4]:
flow = flow[flow['TRAV DESC'] == '120S PC']
flow.shape[0]

6326

In [5]:
flow = flow[flow.AREA != 'F11 GENERAL']
flow.head()
step = flow['WS'][:-1].tolist()
#print(step)

In [6]:
Qty = data.get('Qty')

In [7]:
WS_EQ = pd.concat([Qty['WS NAME'],Qty['EQUIP ID']],axis=1)
WS_EQ.head() #機台對應 WS
WS_NAME = WS_EQ['WS NAME'].tolist()
#print(WS_NAME)

In [8]:
WS_EQ.head()

WS NAME    EQUIP ID
0  11-3ABON_ZFB_N2P  AN2PB80101
1  11-3ABON_ZFB_N2P  AN2PB80102
2  11-3ABON_ZFB_N2P  AN2PB80103
3  11-3ABON_ZFB_N2P  AN2PB80104
4  11-3ABON_ZFB_N2P  AN2PB80105

In [9]:
wafer = input('Please enter the quantity of wafers:')
wafer_m = []
for i in step:
    if i in WS_NAME:
        w = round(int(wafer)/WS_EQ.groupby(['WS NAME']).size()[i],2)
        wafer_m.append(w)
    else:
        wafer_m.append(0)
    #print(i)
#print ('Number of wafers in each machine:',wafer_m)


Please enter the quantity of wafers:600


In [24]:
change_step = input('Please enter the changed step (start from zero): ') #修改機台數的步驟
add_machine = input('Please enter the quantity of equipment added: ')
#change_data = wafer_in_each_machine.iloc[int(change_step)-1:int(change_step)+2,] #提取該步驟
change_WS = step[int(change_step)-1:int(change_step)+2] #提取索引
#print(change_step)
#print(change_data)
#print(change_WS)

Please enter the changed step (start from zero): 611
Please enter the quantity of equipment added: 3


In [25]:
col = ['3','4','7','8','9','C','D','E']
#print(wafer_in_each_machine)
wafer_in_each_machine = pd.DataFrame(columns = col)
machine_num = pd.DataFrame(columns = col)
for i in change_WS:
    f1 = WS_EQ[(WS_EQ['WS NAME'] == i) & (WS_EQ['EQUIP ID'].str.get(5) == '3')].shape[0]
    f2 = WS_EQ[(WS_EQ['WS NAME'] == i) & (WS_EQ['EQUIP ID'].str.get(5) == '4')].shape[0]
    f3 = WS_EQ[(WS_EQ['WS NAME'] == i) & (WS_EQ['EQUIP ID'].str.get(5) == '7')].shape[0]
    f4 = WS_EQ[(WS_EQ['WS NAME'] == i) & (WS_EQ['EQUIP ID'].str.get(5) == '8')].shape[0]
    f5 = WS_EQ[(WS_EQ['WS NAME'] == i) & (WS_EQ['EQUIP ID'].str.get(5) == '9')].shape[0]
    f6 = WS_EQ[(WS_EQ['WS NAME'] == i) & (WS_EQ['EQUIP ID'].str.get(5) == 'C')].shape[0]
    f7 = WS_EQ[(WS_EQ['WS NAME'] == i) & (WS_EQ['EQUIP ID'].str.get(5) == 'D')].shape[0]
    f8 = WS_EQ[(WS_EQ['WS NAME'] == i) & (WS_EQ['EQUIP ID'].str.get(5) == 'E')].shape[0]
    machine = np.array([f1,f2,f3,f4,f5,f6,f7,f8])
    machine_D = pd.DataFrame([machine],columns = col)
    machine_num = machine_num.append(machine_D)
    for j in range(8):
        if i in WS_NAME:
            num = wafer_m[step.index(i)]*machine[j]
        else:
            num = 0
        machine[j] = num
    machine = pd.DataFrame([machine],columns = col)
    #print(machine)
    wafer_in_each_machine = wafer_in_each_machine.append(machine)

In [26]:
machine_num.head()

3  4  7  8  9  C  D  E
0  0  0  1  0  0  0  0  0
0  2  0  2  0  0  0  0  0
0  0  0  2  0  0  0  0  0

In [27]:
def weight(distance,carry,step):
    total_carry = []
    for i in range(len(step)-1):
        carry_weight = np.multiply(carry[i],distance)
        total_carry_step = np.sum(carry_weight)-np.trace(carry_weight) 
        total_carry.append(total_carry_step)
        print (carry_weight)
        print ('Step carriage:',total_carry_step)
        print ('-----------------------------------------')
    print ('Total carriage: ',sum(total_carry))
    return sum(total_carry)

In [42]:
data = wafer_in_each_machine.values #提取部分值 array
Carriage = []
for l in range(8):
    data[1,l] = data[1,l]+int(add_machine)
    a = range(8)
    c_m = []
    for k in range(len(change_WS)-1):
        for j in a:
            for i in a:
                c_n = max(data[k,j]-data[k+1,j],0)*data[k+1,a]//(int(wafer)-data[k+1,j]+1) #避免分母為零
            c_m.append(c_n)      
    c_step_m = np.array(c_m)
    #print(c_step_m)
    #print(c_step_m.shape)
    c_carry = np.vsplit(c_step_m, len(change_WS)-1)
    for i in range(len(change_WS)-1):
        for j in range(8):
            c_carry[i][j][j] = min(data[i,j],data[i+1,j])
            c_carry = np.array(c_carry)
    #print(c_carry)
    #print('---------------------')
    print (col[l])
    weight(distance = np.ones((8,8)),carry = c_carry,step = change_WS)
    Carriage.append(weight(distance = np.ones((8,8)),carry = c_carry,step = change_WS))
    print('==========================================')
    print('                                           ')
    data[1,l] = data[1,l]-int(add_machine)
Carriage = pd.DataFrame([Carriage],columns = col)
Carriage.head()

3
[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [331.0 29.0 330.0 29.0 29.0 29.0 29.0 29.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]]
Step carriage: 505.0
-----------------------------------------
[[0.0 0.0 332.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 29.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 330.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 29.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 29.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 29.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 29.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 29.0 0.0 0.0 0.0 0.0 0.0]]
Step carriage: 506.0
-----------------------------------------
Total carriage:  1011.0
[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [331.0 29.0 330.0 29.0 29.0 29.0 29.0 29.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0

3       4       7       8       9       C       D       E
0  1011.0  1011.0  1005.0  1011.0  1011.0  1011.0  1011.0  1011.0