In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('final.csv')
print(df)

    FG%   3P%   FT%  ORB  DRB  TRB  AST  STL  BLK  TOV  PF  PTS  HOME  RESULT  \
0  50.6  39.4  84.4    7   29   36   25    6    6   10  26  118     1       1   
1  37.2  28.9  88.5   15   34   49   17    8    2   15  22  104     1       0   
2  52.4  44.7  95.2    5   35   40   30    9   10   14  22  123     0       1   
3  41.9  31.3  95.8    7   32   39   22   12    4    9  21  105     0       1   
4  44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1       0   

        DATE  
0  2019/5/31  
1   2019/6/3  
2   2019/6/6  
3   2019/6/9  
4  2019/6/11  


In [3]:
for i in range(40):
    sample = df.sample(n=1, replace=True, axis=0)
    df = pd.concat([df,sample], axis=0, ignore_index=True)
print(df)
    

     FG%   3P%   FT%  ORB  DRB  TRB  AST  STL  BLK  TOV  PF  PTS  HOME  \
0   50.6  39.4  84.4    7   29   36   25    6    6   10  26  118     1   
1   37.2  28.9  88.5   15   34   49   17    8    2   15  22  104     1   
2   52.4  44.7  95.2    5   35   40   30    9   10   14  22  123     0   
3   41.9  31.3  95.8    7   32   39   22   12    4    9  21  105     0   
4   44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1   
5   44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1   
6   41.9  31.3  95.8    7   32   39   22   12    4    9  21  105     0   
7   44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1   
8   41.9  31.3  95.8    7   32   39   22   12    4    9  21  105     0   
9   44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1   
10  50.6  39.4  84.4    7   29   36   25    6    6   10  26  118     1   
11  52.4  44.7  95.2    5   35   40   30    9   10   14  22  123     0   
12  50.6  39.4  84.4    7   29   36   

In [4]:
x_train = df.drop(['DATE','RESULT'],axis = 1)
y_train = df['RESULT']
print(x_train)
print(y_train)

     FG%   3P%   FT%  ORB  DRB  TRB  AST  STL  BLK  TOV  PF  PTS  HOME
0   50.6  39.4  84.4    7   29   36   25    6    6   10  26  118     1
1   37.2  28.9  88.5   15   34   49   17    8    2   15  22  104     1
2   52.4  44.7  95.2    5   35   40   30    9   10   14  22  123     0
3   41.9  31.3  95.8    7   32   39   22   12    4    9  21  105     0
4   44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1
5   44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1
6   41.9  31.3  95.8    7   32   39   22   12    4    9  21  105     0
7   44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1
8   41.9  31.3  95.8    7   32   39   22   12    4    9  21  105     0
9   44.7  25.0  77.8   13   30   43   19    6    5   13  19  105     1
10  50.6  39.4  84.4    7   29   36   25    6    6   10  26  118     1
11  52.4  44.7  95.2    5   35   40   30    9   10   14  22  123     0
12  50.6  39.4  84.4    7   29   36   25    6    6   10  26  118     1
13  41

In [5]:
from sklearn.decomposition import PCA 
pca=PCA(n_components=4)

In [6]:
pca.fit(x_train)
x_train_pca = pca.transform(x_train)
print("original shape:   ", x_train.shape)
print("transformed shape:", x_train_pca.shape)

original shape:    (45, 13)
transformed shape: (45, 4)


In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(x_train_pca, y_train)
print(model.coef_)
print(model.intercept_)

[[-0.44007568  0.62345425 -0.89418441  0.05292947]]
[0.33111493]


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [9]:
df1 = pd.read_csv('final_test.csv')
df_test = df1.drop(df.index[0:5])
x_test = df_test.drop(['DATE','RESULT'],axis = 1)
print(x_test)

pca_test=PCA(n_components=4)
pca_test.fit(x_test)
x_test_pca = pca_test.transform(x_test)

print("original shape:   ", x_test.shape)
print("transformed shape:", x_test_pca.shape)

       FG%     3P%    FT%   ORB    DRB    TRB    AST   STL  BLK    TOV     PF  \
5   45.360  33.860  88.34   9.4  32.00  41.40  22.60  8.20  5.4  12.20  22.00   
6   45.770  32.810  88.75  10.2  32.50  42.70  21.80  8.40  5.0  12.70  21.60   
7   46.880  35.440  89.01   8.4  32.10  40.50  23.90  8.30  6.2  12.10  22.00   
8   44.715  31.990  88.44   9.3  31.75  41.05  22.10  8.75  5.2  11.65  21.15   
9   45.215  33.165  88.56   8.8  31.35  40.15  22.45  8.60  5.1  11.15  22.05   
10  45.830  34.100  89.07   8.6  31.80  40.40  23.10  8.60  5.6  11.60  21.90   
11  44.995  31.360  86.64   9.9  31.55  41.45  21.80  8.15  5.3  12.05  20.95   

       PTS  HOME  
5   111.00     0  
6   109.60     0  
7   112.90     0  
8   108.90     0  
9   109.95     0  
10  111.10     0  
11  108.90     0  
original shape:    (7, 13)
transformed shape: (7, 4)


In [10]:
print(x_test_pca)

[[ 0.65132276  0.57977013  0.15830297  0.59481044]
 [-1.32124494  1.97484532 -0.68237502 -0.05734259]
 [ 4.09842268  0.32745673  0.56895144 -0.29086434]
 [-1.99406606 -0.7064065  -0.526282   -0.41685355]
 [-0.06670464 -1.43792746 -0.4607482   0.36425571]
 [ 1.66494336 -0.60717509 -0.33196281 -0.14185575]
 [-3.03267317 -0.13056313  1.27411362 -0.05214991]]


In [11]:
prob =np.round(model.predict_proba(x_test_pca),3)
print(np.delete(prob,1,1))

[[0.427]
 [0.06 ]
 [0.857]
 [0.229]
 [0.526]
 [0.62 ]
 [0.391]]


In [12]:
prob =np.round(model.predict_proba(x_test_pca))
print(np.delete(prob,1,1))

[[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]]
