In [71]:
import numpy as np
import pandas as pd

In [81]:
df = pd.read_csv('final_test.csv')
print(df)

       FG%     3P%    FT%   ORB    DRB    TRB    AST    STL   BLK    TOV  \
0   50.600  39.400  84.40   7.0  29.00  36.00  25.00   6.00   6.0  10.00   
1   37.200  28.900  88.50  15.0  34.00  49.00  17.00   8.00   2.0  15.00   
2   52.400  44.700  95.20   5.0  35.00  40.00  30.00   9.00  10.0  14.00   
3   41.900  31.300  95.80   7.0  32.00  39.00  22.00  12.00   4.0   9.00   
4   44.700  25.000  77.80  13.0  30.00  43.00  19.00   6.00   5.0  13.00   
5   45.360  33.860  88.34   9.4  32.00  41.40  22.60   8.20   5.4  12.20   
6   45.770  32.810  88.75  10.2  32.50  42.70  21.80   8.40   5.0  12.70   
7   46.880  35.440  89.01   8.4  32.10  40.50  23.90   8.30   6.2  12.10   
8   44.715  31.990  88.44   9.3  31.75  41.05  22.10   8.75   5.2  11.65   
9   45.215  33.165  88.56   8.8  31.35  40.15  22.45   8.60   5.1  11.15   
10  45.830  34.100  89.07   8.6  31.80  40.40  23.10   8.60   5.6  11.60   
11  44.995  31.360  86.64   9.9  31.55  41.45  21.80   8.15   5.3  12.05   

       PF  

In [82]:
df_train = df.drop(df.index[-7:])
x_train = df_train.drop(['DATE','RESULT'],axis = 1)
y_train = df_train['RESULT']
print(x_train)
print(y_train)

    FG%   3P%   FT%   ORB   DRB   TRB   AST   STL   BLK   TOV    PF    PTS  \
0  50.6  39.4  84.4   7.0  29.0  36.0  25.0   6.0   6.0  10.0  26.0  118.0   
1  37.2  28.9  88.5  15.0  34.0  49.0  17.0   8.0   2.0  15.0  22.0  104.0   
2  52.4  44.7  95.2   5.0  35.0  40.0  30.0   9.0  10.0  14.0  22.0  123.0   
3  41.9  31.3  95.8   7.0  32.0  39.0  22.0  12.0   4.0   9.0  21.0  105.0   
4  44.7  25.0  77.8  13.0  30.0  43.0  19.0   6.0   5.0  13.0  19.0  105.0   

   HOME  
0     1  
1     1  
2     0  
3     0  
4     1  
0    1.0
1    0.0
2    1.0
3    1.0
4    0.0
Name: RESULT, dtype: float64


In [83]:
from sklearn.decomposition import PCA 
pca=PCA(n_components=4)

In [84]:
pca.fit(x_train)
x_train_pca = pca.transform(x_train)
print("original shape:   ", x_train.shape)
print("transformed shape:", x_train_pca.shape)

original shape:    (5, 13)
transformed shape: (5, 4)


In [85]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(x_train_pca, y_train)
print(model.coef_)
print(model.intercept_)

[[0.32382649 0.17447657 0.3694957  0.08181861]]
[0.06856591]


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [86]:
df_test = df.drop(df.index[0:5])
x_test = df_test.drop(['DATE','RESULT'],axis = 1)
print(x_test)

pca_test=PCA(n_components=4)
pca_test.fit(x_test)
x_test_pca = pca_test.transform(x_test)

print("original shape:   ", x_test.shape)
print("transformed shape:", x_test_pca.shape)

       FG%     3P%    FT%   ORB    DRB    TRB    AST   STL  BLK    TOV     PF  \
5   45.360  33.860  88.34   9.4  32.00  41.40  22.60  8.20  5.4  12.20  22.00   
6   45.770  32.810  88.75  10.2  32.50  42.70  21.80  8.40  5.0  12.70  21.60   
7   46.880  35.440  89.01   8.4  32.10  40.50  23.90  8.30  6.2  12.10  22.00   
8   44.715  31.990  88.44   9.3  31.75  41.05  22.10  8.75  5.2  11.65  21.15   
9   45.215  33.165  88.56   8.8  31.35  40.15  22.45  8.60  5.1  11.15  22.05   
10  45.830  34.100  89.07   8.6  31.80  40.40  23.10  8.60  5.6  11.60  21.90   
11  44.995  31.360  86.64   9.9  31.55  41.45  21.80  8.15  5.3  12.05  20.95   

       PTS  HOME  
5   111.00     0  
6   109.60     0  
7   112.90     0  
8   108.90     0  
9   109.95     0  
10  111.10     0  
11  108.90     0  
original shape:    (7, 13)
transformed shape: (7, 4)


In [87]:
print(x_test_pca)

[[ 0.65132276  0.57977013  0.15830297  0.59481044]
 [-1.32124494  1.97484532 -0.68237502 -0.05734259]
 [ 4.09842268  0.32745673  0.56895144 -0.29086434]
 [-1.99406606 -0.7064065  -0.526282   -0.41685355]
 [-0.06670464 -1.43792746 -0.4607482   0.36425571]
 [ 1.66494336 -0.60717509 -0.33196281 -0.14185575]
 [-3.03267317 -0.13056313  1.27411362 -0.05214991]]


In [88]:
prob =np.round(model.predict_proba(x_test_pca),3)
print(np.delete(prob,1,1))

[[0.38 ]
 [0.567]
 [0.163]
 [0.717]
 [0.585]
 [0.409]
 [0.615]]


In [89]:
prob =np.round(model.predict_proba(x_test_pca))
print(np.delete(prob,1,1))

[[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]]
