In [44]:
import numpy as np
import pandas as pd

In [45]:
df = pd.read_csv('train.csv')
print(df)

   Team   FG%   3P%   FT%  ORB  DRB  TRB  AST  STL  BLK  TOV  PF  PTS  HOME  \
0   TOR  48.5  36.7  85.0   17   29   46   27    6    5   15  22  128     0   
1   TOR  47.6  23.1  69.2    5   35   40   28    5   11   19  18   93     1   
2   POR  56.5  53.1  75.0    6   37   43   29   11   10   15  22  125     1   
3   POR  42.5  29.5  40.0   14   45   59   36   10    9   15  19  109     1   
4   POR  50.0  48.0  82.1    5   37   42   27    9    4   12  18  115     0   
5   POR  40.2  34.2  88.9   18   31   49   26    1    9    9  26  107     0   
6   MIL  48.3  35.7  77.3    8   30   38   31    5    6   18  22  111     1   
7   MIL  44.9  41.3  85.7    6   37   43   32    7    6   18  20  105     0   
8   UTA  56.3  52.6  88.9    8   35   43   27   10    6   16  23  124     0   
9   UTA  40.0  32.3  94.4   10   38   48   18   10    9   12  21  103     0   
10  UTA  49.4  31.7  66.7    5   35   40   29   12    7    7  20  115     1   
11  PHI  46.6  28.9  68.8    9   28   37   30   13  

In [46]:
x_train = df.drop(['Team','DATE','RESULT'],axis = 1)
y_train = df['RESULT']

In [47]:
from sklearn.decomposition import PCA 
pca=PCA(n_components=4)

In [48]:
pca.fit(x_train)
x_train_pca = pca.transform(x_train)
print("original shape:   ", x_train.shape)
print("transformed shape:", x_train_pca.shape)

original shape:    (17, 13)
transformed shape: (17, 4)


In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(x_train_pca, y_train)
print(model.coef_)
print(model.intercept_)

[[-0.14480804 -0.1253852  -0.18509536 -0.21937863]]
[-0.05114789]


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [50]:
df1 = pd.read_csv('test.csv')
print(df1)

    FG%   3P%   FT%  ORB  DRB  TRB  AST  STL  BLK  TOV  PF  PTS  HOME  RESULT  \
0  50.0  51.5  83.3   11   31   42   30   13    8   14  24  116     1       1   
1  51.2  31.0  77.8   12   38   50   30    4    9   16  21  114     1       1   
2  48.8  30.8  87.0    7   42   49   27    9    5   14  24  110     0       1   
3  46.5  30.8  78.9   15   41   56   30   10    5   15  17  119     0       1   

   DATE  
0   NaN  
1   NaN  
2   NaN  
3   NaN  


In [51]:
x_test = df1.drop(['DATE','RESULT'],axis = 1)
y_test = df1['RESULT']
pca_test=PCA(n_components=4)
pca_test.fit(x_test)
x_test_pca = pca_test.transform(x_test)

print("original shape:   ", x_test.shape)
print("transformed shape:", x_test_pca.shape)

original shape:    (4, 13)
transformed shape: (4, 4)


In [52]:
print(x_test_pca)

[[ 1.92000948e+01 -1.44682869e+00 -5.30843427e-01 -3.72965547e-16]
 [-5.48773135e+00 -1.27264051e+00  6.91367780e+00  3.73746173e-14]
 [-4.58499256e+00  1.00425238e+01 -2.22919484e+00 -1.96665600e-14]
 [-9.12737094e+00 -7.32305458e+00 -4.15363954e+00 -1.33938000e-14]]


In [43]:
prob =np.round(model.predict_proba(x_test_pca))
print(np.delete(prob,1,1))

[[1.]
 [1.]
 [1.]
 [0.]]
