In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('MILvsTOR_Train.csv')
print(df)

   Team   FG%   3P%   FT%  ORB  DRB  TRB  AST  STL  BLK  TOV  PF  PTS  HOME  \
0   TOR  48.9  42.2  78.9    8   49   57   28    5    4   17  21  124     1   
1   TOR  41.4  38.5  85.0    9   36   45   22    6    7   13  13  104     0   
2   TOR  49.4  37.8  81.5    4   34   38   29    9    2   16  20  116     1   
3   TOR  49.4  36.8  76.5    7   43   50   21   13    6   20  16  105     0   
4   GSW  51.5  25.7  77.8   13   33   46   33   11    7   12  23  134     0   
5   GSW  39.1  17.9  69.6   15   39   54   18   10    3   19  21   95     1   
6   POR  43.5  38.1  87.5   12   30   42   26    2    1   12  16  103     0   
7   POR  52.8  33.3  82.4   13   46   59   34    8    2   14  23  143     1   
8   UTA  46.9  36.0  81.3   10   36   46   27   10    6   11  19  114     1   
9   UTA  38.5  38.5  73.3   17   36   53   20    6   10   15  22  111     0   
10  PHI  41.0  30.2  93.3    9   42   51   24    7   10   11  27  123     1   
11  PHI  45.3  32.0  82.1   10   35   45   25    9  

In [3]:
x_train = df.drop(['Team','DATE','RESULT'],axis = 1)
y_train = df['RESULT']

In [4]:
from sklearn.decomposition import PCA 
pca=PCA(n_components=4)

In [5]:
pca.fit(x_train)
x_train_pca = pca.transform(x_train)
print("original shape:   ", x_train.shape)
print("transformed shape:", x_train_pca.shape)

original shape:    (15, 13)
transformed shape: (15, 4)


In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(x_train_pca, y_train)
print(model.coef_)
print(model.intercept_)

[[ 0.13651218 -0.10944393  0.21635035  0.10041766]]
[0.61896259]


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [8]:
df1 = pd.read_csv('MILvsTOR_Test.csv')
print(df1)

    FG%   3P%   FT%  ORB  DRB  TRB  AST  STL  BLK  TOV  PF  PTS  HOME  RESULT  \
0  39.8  25.0  85.2   15   45   60   21    8   11   13  16  108     1       1   
1  46.7  31.7  74.3   11   42   53   27    6    4    7  26  125     1       1   
2  37.3  31.8  66.7   13   50   63   22   14    5   20  30  112     0       0   
3  46.3  31.4  65.4    7   33   40   30    8    7   12  22  102     0       0   
4  45.2  32.3  72.2    8   45   53   26    2    2   11  22   99     1       0   
5  40.0  35.3  71.0   12   30   42   19    7    7   11  22   94     0       0   

        DATE  
0  2019/5/16  
1  2019/5/18  
2  2019/5/20  
3  2019/5/22  
4  2019/5/24  
5  2019/5/26  


In [9]:
x_test = df1.drop(['DATE','RESULT'],axis = 1)
y_test = df1['RESULT']
pca_test=PCA(n_components=4)
pca_test.fit(x_test)
x_test_pca = pca_test.transform(x_test)

print("original shape:   ", x_test.shape)
print("transformed shape:", x_test_pca.shape)

original shape:    (6, 13)
transformed shape: (6, 4)


In [10]:
print(x_test_pca)

[[-10.89987016 -13.22265875  -9.60115592  -1.69759777]
 [-11.54565843  14.46363078  -7.7238221   -1.38431483]
 [-15.4217524   -0.79084098  14.64352571  -2.2687896 ]
 [ 15.67756768   7.50297335   0.60317219  -0.27136339]
 [  3.40081021  -2.76008594   1.07251845  11.10295226]
 [ 18.7889031   -5.19301846   1.00576167  -5.48088666]]


In [12]:
prob =np.round(model.predict_proba(x_test_pca),3)
print(np.delete(prob,1,1))

[[0.842]
 [0.987]
 [0.176]
 [0.115]
 [0.061]
 [0.032]]


In [13]:
prob =np.round(model.predict_proba(x_test_pca))
print(np.delete(prob,1,1))

[[1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]
